source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/lxz555/spec.git'

platform :ios, '7.0'
pod 'AFNetworking'
pod 'Masonry', '~> 0.6.2'
pod 'SDWebImage'
pod 'MBProgressHUD'
pod 'MWPhotoBrowser', '~>2.1.1'
pod 'JSPatch'

#制作的自己的pod仓库，把代码放进去，供方便的使用。
#pod 'ColorLib', :git =>'https://github.com/lxz555/ColorLib.git', :tag => 'v0.2.0'
#成功，增加source 'https://github.com/lxz555/spec.git'，就是我自己管理了一份spec，加到source中，可以不用写网址了。
pod 'ColorLib’, '~>0.2.0’
pod 'XZLocation’, '~>0.1.0’